blank_issues_enabled: true
contact_links:
  - name: 🗯 Discussions forum
    url: https://kennethenevoldsen/tomsup/discussions
    about: Usage questions, general discussion and anything else that isn't a bug report or a feature request.
  - name: tomsup usage guides & package references
    url: https://kennethenevoldsen.io/tomsup/
    about: Everything you need to know about tomsup and how to use it.
  - name: 🛠 Submit a pull request
    url: https://github.com/kennethenevoldsen/tomsup/pulls
    about: Did you spot a mistake and know how to fix it? Feel free to submit a PR and contribute!
